base_url = "https://josh.is-cool.dev"
# base_url = "https://phocks.surge.sh"

title = "Josh's Cool Dev Blog"
default_language = "en"

# Zola theme
theme = "terminimal"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Sass compilation is required
compile_sass = true

# The theme supports feeds (RSS and ATOM)
generate_feed = true

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filename = "atom.xml"

# Optional: enable tags
taxonomies = [{ name = "tags" }]

# Code highlighting
[markdown]
highlight_code = true
# highlight_theme = "1337"
highlight_themes_css = [
  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
]

[extra]

# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "green-auto"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "green-auto"

# The logo text - defaults to "Terminimal theme"
logo_text = "josh@thinkpad:~/src$"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Joshua Byrd"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
# copyright_html = "My custom&nbsp;<b>copyright</b>"

# menu is enabled by adding menu_items (optional)
menu_items = [
  # each of these is optional, name and url are required
  # $BASE_URL is going to be substituted by base_url from configuration
  { name = "blog", url = "$BASE_URL" },

  # tags should only be enabled if you have "tags" taxonomy
  # see documentation below for more details
  { name = "about", url = "$BASE_URL/about" },
  { name = "archive", url = "$BASE_URL/archive" },
  { name = "tags", url = "$BASE_URL/tags" },
  { name = "rss", url = "$BASE_URL/atom.xml" },

  # set newtab to true to make the link open in new tab
  # { name = "github", url = "https://github.com/pawroman/zola-theme-terminimal", newtab = true },
]

# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Would you like to know more?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
favicon = "/favicon.png"
favicon_mimetype = "image/png"

# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "combined"
